// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCONfZ_B-yTrE91aK9kBVCGdLx4On0ToYo',
    appId: '1:985770940523:web:74f948e11fc51ebcfdf92e',
    messagingSenderId: '985770940523',
    projectId: 'staras-89a8a',
    authDomain: 'staras-89a8a.firebaseapp.com',
    storageBucket: 'staras-89a8a.appspot.com',
    measurementId: 'G-2K6QZX4R0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdASi_XL7lk7MoTlGDBvLuJNSg-y6-OAM',
    appId: '1:985770940523:android:0f22d8112ac6cb39fdf92e',
    messagingSenderId: '985770940523',
    projectId: 'staras-89a8a',
    storageBucket: 'staras-89a8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyUw0VNrT3gxMGwtDPSrqujWXIWqxKF5w',
    appId: '1:985770940523:ios:0bbc59237497cc3cfdf92e',
    messagingSenderId: '985770940523',
    projectId: 'staras-89a8a',
    storageBucket: 'staras-89a8a.appspot.com',
    iosBundleId: 'com.example.starasCheckin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyUw0VNrT3gxMGwtDPSrqujWXIWqxKF5w',
    appId: '1:985770940523:ios:94c627e00c3f2c94fdf92e',
    messagingSenderId: '985770940523',
    projectId: 'staras-89a8a',
    storageBucket: 'staras-89a8a.appspot.com',
    iosBundleId: 'com.example.starasCheckin.RunnerTests',
  );
}
